### PR TITLE
Addition of DHL_Products class

### PR DESCRIPTION
**Pull request by Dakror**
This class contains all dhl products and their attributes, such as compatible services, min and max sizes and weights, as well as localized namings.

I used the official infographics and charts of the DHL dev website to assemble this list.

PS: This is my first ever PR on Github, tell me if i'm doing something wrong :)

### CODE REVIEW

**Comment by Petschko** [comment]
Hello,
first thanks for contributing. Your Pull-Request looks fine so far, please use an extra branch next time, so when you adding more changes to your master branch these changes don't appear here. Now if you add stuff to your master branch these will also come in here.

Now to your Pull-Request: I don't get for what you want to use this? Do you have an example or such stuff I'm unsure if I should merge this because may it confuses more than it helps?

Maybe more details would help me to understand what you want to do with it^^

**Comment by Dakror** [comment]
Hi,
okay yes I understand about the branching.

Well we use your api for business customers running online shops. They use a UI for creating shipments within the admin office of their store. 
To know which services, and min-max weights and sizes are applicable to the various DHL products, this list is needed and so i assembled it from the tables given by DHL. 

It is not a very innovative or brilliant addition to your already very nice SDK, it's just a time saver really. 

For example my shipment creation UI has a html `<select>` for the desired DHL package type, and upon selection displays checkboxes for all available services such as Go Green, Day of delivery, and so on, as well as providing the internal validation systems with information to quickly validate user input for package sizes and weight.

**Comment by Petschko** [comment]
The Idea is not bad, I will merge it but change it a little plus I can use this for validation =)

I will merge it with my changes on weekend then

**Comment by Petschko** [comment]
Done =) I used Objects for every Product-Info instead of using so long arrays. You can access them now like this:

````php
// Get Max-Height for "NATIONAL_PACKAGE"
DHL_ProductInfo::getInfo(DHL_ShipmentDetails::PRODUCT_TYPE_NATIONAL_PACKAGE)->getMaxHeight();
````

**Pull request merged**
