### PR TITLE
Added support for notification e-mail

### PR DESCRIPTION
**Pull request by aschempp**
See ShipmentOrder.Shipment.ShipmentDetails.Notification.recipientEmailAddress

### CODE REVIEW

**Comment by Petschko** [comment]
This already exists, but I think your change makes more sense than my previous implementation...
https://github.com/Petschko/dhl-php-sdk/blob/master/includes/BusinessShipment.php#L749

I need to modify your PR or better say remove my current implementation, so please be patient

**Comment by aschempp** [comment]
interesting, I didn't find that! I don't think you should remove/change your implementation because that would be a BC break. In my opinion you can close this pull request :-)

**Comment by Petschko** [comment]
I not remove it completly, I will mark it as deprecated, so that BC is given

**Comment by Petschko** [comment]
@aschempp this is also important to fixing this issue:
https://github.com/Petschko/dhl-php-sdk/issues/29

There can be an E-Mail for each label! So this change is important... I will fix this issue today, I need to organize it a bit

**Pull request merged**
