### PR TITLE
Composerify the library

### PR DESCRIPTION
**Pull request by cedricziel**
To enable usage in other projects as a library, the code has been
transformed to use the namespace "Petschko\DHL" and a composer.json
file has been added.

* use class autoloading through composer instead of manually requiring

ToDo:

Amend the documentation to reflect the new class names

### CODE REVIEW

**Comment by cedricziel** [comment]
Hi there :)

I have gone ahead and Transformed the library to be able to consume it with the composer dependency management system (https://getcomposer.org/). Please tell me, if I should adjust the namespace or the license in the composer manifest.

**Comment by pfandie** [comment]
actually @cedricziel did excatly what i need right now.
my intention was to add composer und luckily he already made a feature branch for this ;)
looks quite good

**Comment by cedricziel** [comment]
Alright, I'll add the necessary documentation then.

**Comment by Petschko** [comment]
> Please tell me, if I should adjust the namespace or the license in the composer manifest.
@cedricziel It looks fine to me =)

> Alright, I'll add the necessary documentation then.
That would be great :) If you did that I can merge your branch. Thanks for your awesome edit

**Comment by cedricziel** [comment]
Cool :)

BTW: you should reserve the `petschko/dhl-php-sdk` key on packagist.com now, @Petschko

**Comment by pfandie** [comment]
nice to see the instant response from you guys.
it looks like i can implement the lib via composer today :)

**Comment by cedricziel** [comment]
Alright, please have a look at the adjusted README. I just added the short section about composer and adjusted the usage of `DHL_*` class names to `\Petschko\DHL\*` namespaced references.

**Comment by cedricziel** [comment]
Ahh, I see - you can use both. I didnt know that an thought `LICENSE` would be the correct filename / term. Should I rebase and drop that commit?

**Comment by Petschko** [comment]
Yes on the first view it looks okay to me. Thanks for fixing the indentations in the README^^ Was not aware that you just need 3 ` for displaying Code =)

> Ahh, I see - you can use both. I didnt know that an thought LICENSE would be the correct filename / term. Should I rebase and drop that commit?

If it works too, you can keep these changes ;) I'm okay with it

**Comment by cedricziel** [comment]
perfect - ready to go then :)

**Comment by cedricziel** [comment]
Thx for the merge!

**Pull request merged**
